import { expect, test } from '@playwright/test'

test('By Mail exchanges turns between isolated devices and rejoins from a link', async ({ page: jack, browser }) => {
  const investigatorsContext = await browser.newContext()
  await investigatorsContext.addInitScript(() => localStorage.setItem('whitehall-mystery.show-jack-peek', 'true'))
  const investigators = await investigatorsContext.newPage()
  const recoveryContext = await browser.newContext()
  try {
    await jack.goto('/')
    const origin = jack.url()
    await jack.getByRole('button', { name: 'New game', exact: true }).click()
    await jack.getByRole('button', { name: 'By Mail', exact: true }).click()
    await jack.getByRole('button', { name: 'Start new game as Jack' }).click()
    for (const id of [33, 46, 147, 159]) await jack.getByLabel(`Location ${id}, selectable`, { exact: true }).click()
    await jack.getByRole('button', { name: 'Lock in four locations' }).click()
    await expect(jack.getByRole('heading', { name: 'Waiting for the investigators' })).toBeVisible()
    const invitation = await jack.getByLabel('Outgoing game text').inputValue()
    const savedAfterInvitation = await jack.evaluate(() => localStorage.getItem('whitehall-mystery.by-mail.v1')!)
    expect(invitation.length).toBe(26)
    expect(invitation).toMatch(/^01-/)
    await jack.context().grantPermissions(['clipboard-read', 'clipboard-write'])
    await jack.getByRole('button', { name: 'Copy text', exact: true }).click()
    expect(await jack.evaluate(() => navigator.clipboard.readText())).toBe(invitation)
    await jack.getByRole('button', { name: 'Copy link', exact: true }).click()
    expect(await jack.evaluate(() => navigator.clipboard.readText())).toBe(`${origin}#mail=${invitation}`)
    await jack.setViewportSize({ width: 390, height: 844 })
    expect(await jack.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await jack.screenshot({ path: 'test-results/by-mail-mobile.png', fullPage: true })
    await jack.setViewportSize({ width: 1280, height: 900 })
    await investigators.goto(`${origin}#mail=${invitation}`)
    await investigators.getByLabel('Game text or link from your partner').fill(invitation.slice(3))
    await investigators.getByRole('button', { name: 'Join existing game', exact: true }).click()
    await expect(investigators.getByRole('status')).toContainText('must start with a two-digit turn number and a hyphen')
    await investigators.getByLabel('Game text or link from your partner').fill(invitation)
    await investigators.getByRole('button', { name: 'Join existing game', exact: true }).click()
    await expect(investigators.getByRole('heading', { name: 'Deploy the Yellow Investigator' })).toBeVisible()
    await expect(investigators.locator('.jack-peek-toggle')).toHaveCount(0)
    for (const name of ['Undo Side', 'Undo', 'Redo', 'Redo Side', 'Rand', 'Rand Side']) {
      await expect(investigators.getByLabel('Action history controls').getByRole('button', { name, exact: true })).toBeVisible()
    }
    await expect(investigators.getByRole('button', { name: 'Undo Side', exact: true })).toBeDisabled()
    await expect(investigators.getByRole('button', { name: 'Redo Side', exact: true })).toBeDisabled()
    await expect(investigators.getByLabel('inv auto', { exact: true })).toBeVisible()
    await expect(investigators.locator('.private-discovery, .jack-marker')).toHaveCount(0)
    await investigators.screenshot({ path: 'test-results/by-mail-investigators.png', fullPage: true })
    for (let i = 0; i < 3; i++) await investigators.getByLabel('Available deployment crossings').getByRole('button').first().click()
    await expect(investigators.getByRole('heading', { name: 'Waiting for Jack' })).toBeVisible()
    await investigators.reload()
    await expect(investigators.getByRole('heading', { name: 'Waiting for Jack' })).toBeVisible()
    const deployment = await investigators.getByLabel('Outgoing game text').inputValue()
    expect(deployment).toMatch(/^02-/)
    await investigators.getByRole('button', { name: 'Show board', exact: true }).click()
    await expect(investigators.locator('svg.game-board')).toBeVisible()
    await expect(investigators.locator('.jack-marker, .track-location, .jack-peek-toggle')).toHaveCount(0)
    await expect(investigators.getByRole('button', { name: 'Rand', exact: true })).toBeDisabled()
    await investigators.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(investigators.getByRole('heading', { name: 'Deploy the Red Investigator' })).toBeVisible()
    await investigators.reload()
    await investigators.getByRole('button', { name: 'Redo', exact: true }).click()
    await expect(investigators.getByRole('button', { name: 'Show sharing', exact: true })).toBeVisible()
    await investigators.getByRole('button', { name: 'Show sharing', exact: true }).click()
    await expect(investigators.getByLabel('Outgoing game text')).toHaveValue(deployment)
    await jack.getByLabel('Game text or link from your partner').fill(deployment)
    await jack.getByRole('button', { name: 'Load partner’s reply' }).click()
    await expect(jack.getByRole('heading', { name: 'Jack: Choose the Starting Location' })).toBeVisible()
    await jack.getByLabel('Secret Discovery Locations').getByRole('button').first().click()
    await jack.getByLabel('Legal Jack destinations').getByRole('button').first().click()
    await jack.reload()
    await expect(jack.getByRole('button', { name: 'Record move privately' })).toBeEnabled()
    await jack.getByRole('button', { name: 'Record move privately' }).click()
    const move = await jack.getByLabel('Outgoing game text').inputValue()
    expect(move).toMatch(/^03-/)
    await jack.getByRole('button', { name: 'Show board', exact: true }).click()
    await expect(jack.locator('.jack-marker')).toBeVisible()
    await jack.reload()
    await expect(jack.getByRole('button', { name: 'Show sharing', exact: true })).toBeVisible()
    await expect(jack.getByRole('button', { name: 'Rand Side', exact: true })).toBeDisabled()
    await jack.getByRole('button', { name: 'Show sharing', exact: true }).click()
    await investigators.getByLabel('Game text or link from your partner').fill(move)
    await investigators.getByRole('button', { name: 'Load partner’s reply' }).click()
    await expect(investigators.locator('.jack-marker, .track-location, .jack-peek-toggle')).toHaveCount(0)
    await investigators.getByLabel('inv auto', { exact: true }).check()
    for (const color of ['yellow', 'blue', 'red']) await investigators.getByLabel(`Legal ${color} Investigator destinations`).getByRole('button').first().click()
    await expect(investigators.getByRole('heading', { name: 'Waiting for Jack' })).toBeVisible()
    await investigators.getByRole('button', { name: 'Show board', exact: true }).click()
    await expect(investigators.getByLabel('inv auto', { exact: true })).toBeChecked()
    await expect(investigators.locator('.jack-marker, .track-location, .jack-peek-toggle')).toHaveCount(0)
    await investigators.getByRole('button', { name: 'Show sharing', exact: true }).click()
    const reply = await investigators.getByLabel('Outgoing game text').inputValue()
    expect(reply).toMatch(/^04-/)
    const recovered = await recoveryContext.newPage()
    await recovered.goto(`${origin}#mail=${reply}`)
    await recovered.getByRole('button', { name: 'Join existing game', exact: true }).click()
    await expect(recovered.getByRole('heading', { name: 'Jack: Escape in the Night' })).toBeVisible()
    await expect(recovered.locator('.track-location')).not.toHaveCount(0)
    await expect(recovered.getByText(/This update includes/)).toHaveCount(0)
    await recovered.reload()
    await expect(recovered.getByRole('heading', { name: 'Jack: Escape in the Night' })).toBeVisible()
    await jack.getByLabel('Game text or link from your partner').fill(invitation)
    await jack.getByRole('button', { name: 'Load partner’s reply' }).click()
    await expect(jack.getByText('This message is addressed to the other player.', { exact: false })).toBeVisible()
    await jack.getByLabel('Game text or link from your partner').fill(reply)
    await jack.getByRole('button', { name: 'Load partner’s reply' }).click()
    await expect(jack.getByRole('heading', { name: 'Jack: Escape in the Night' })).toBeVisible()
    await expect(jack.getByText(/This update includes/)).toHaveCount(0)

    // Simulate a device still waiting at the original invitation, then load the same reply.
    await jack.evaluate(saved => localStorage.setItem('whitehall-mystery.by-mail.v1', saved), savedAfterInvitation)
    await jack.reload()
    await jack.getByLabel('Game text or link from your partner').fill(reply)
    await jack.getByRole('button', { name: /Load partner.s reply/ }).click()
    await expect(jack.getByRole('heading', { name: 'Jack: Escape in the Night' })).toBeVisible()
    await expect(jack.getByRole('status').filter({ hasText: 'This update includes 3 player turns' })).toBeVisible()
  } finally {
    await investigatorsContext.close()
    await recoveryContext.close()
  }
})

test('By Mail random controls and action count survive undo, redo and refresh', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'New game', exact: true }).click()
  await page.getByRole('button', { name: 'By Mail', exact: true }).click()
  await page.getByRole('button', { name: 'Start new game as Jack' }).click()
  await expect(page.getByRole('heading', { name: 'Turn 1 in progress', exact: true })).toBeVisible()
  await expect(page.getByLabel('0 player actions')).toBeVisible()
  await page.getByRole('button', { name: 'Rand', exact: true }).click()
  await expect(page.getByLabel('1 player actions')).toBeVisible()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Turn 1 in progress', exact: true })).toBeVisible()
  await expect(page.getByLabel('0 player actions')).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(page.getByLabel('1 player actions')).toBeVisible()
  await page.getByRole('button', { name: 'Rand Side', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Waiting for the investigators' })).toBeVisible()
  const original = await page.getByLabel('Outgoing game text').inputValue()
  await page.getByRole('button', { name: 'Show board', exact: true }).click()
  await expect(page.getByLabel('5 player actions')).toBeVisible()
  await page.getByRole('button', { name: 'Undo Side', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Jack: Plan the Crime' })).toBeVisible()
  await expect(page.getByLabel('Outgoing game text')).toHaveCount(0)
  await expect(page.getByLabel('0 player actions')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Undo Side', exact: true })).toBeDisabled()
  await page.reload()
  await page.getByRole('button', { name: 'Redo Side', exact: true }).click()
  await expect(page.getByLabel('5 player actions')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Redo Side', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Show sharing', exact: true }).click()
  await expect(page.getByLabel('Outgoing game text')).toHaveValue(original)
})

test('turn timestamps and corrections work during a turn, with review for broader changes', async ({ page: jack, browser }) => {
  const context = await browser.newContext({ timezoneId: 'America/Chicago' })
  const bob = await context.newPage()
  const startJack = async (locations: number[]) => {
    await jack.getByRole('button', { name: 'New game', exact: true }).click()
    await jack.getByRole('button', { name: 'By Mail', exact: true }).click()
    await jack.getByRole('button', { name: 'Start new game as Jack' }).click()
    for (const id of locations) await jack.getByLabel(`Location ${id}, selectable`, { exact: true }).click()
    await jack.getByRole('button', { name: 'Lock in four locations' }).click()
  }
  try {
    await jack.clock.setFixedTime(new Date('2026-09-11T10:00:00Z'))
    await jack.goto('/')
    const origin = jack.url()
    await startJack([33, 46, 147, 159])
    await expect(jack.getByRole('heading', { name: 'Turn 1, Sep11 10:00:00 UTC', exact: true })).toBeVisible()
    const initial = await jack.getByLabel('Outgoing game text').inputValue()
    await bob.goto(`${origin}#mail=${initial}`)
    await bob.getByRole('button', { name: 'Join existing game', exact: true }).click()
    await expect(bob.locator('.mail-heading time')).toHaveText('2026-09-11 05:00:00 CDT')
    await bob.getByLabel('Available deployment crossings').getByRole('button').first().click()
    await bob.getByRole('button', { name: 'Show sharing', exact: true }).click()
    await expect(bob.getByRole('heading', { name: 'Turn 2 in progress', exact: true })).toBeVisible()
    await bob.getByLabel('Game text or link from your partner').fill(initial)
    await expect(bob.getByRole('button', { name: /Load partner.s reply/ })).toBeDisabled()
    await expect(bob.getByRole('button', { name: /Load partner.s correction/ })).toBeEnabled()

    await jack.getByRole('button', { name: 'Undo side', exact: true }).click()
    await jack.clock.setFixedTime(new Date('2026-09-11T11:00:00Z'))
    for (const id of [34, 46, 147, 159]) await jack.getByLabel(`Location ${id}, selectable`, { exact: true }).click()
    await jack.getByRole('button', { name: 'Lock in four locations' }).click()
    const revised = await jack.getByLabel('Outgoing game text').inputValue()
    await bob.getByLabel('Game text or link from your partner').fill(revised)
    await bob.getByRole('button', { name: /Load partner.s correction/ }).click()
    await expect(bob.getByRole('alertdialog')).toHaveCount(0)
    await expect(bob.getByRole('heading', { name: 'Deploy the Yellow Investigator' })).toBeVisible()
    await expect(bob.locator('.investigator-piece')).toHaveCount(0)
    await expect(bob.getByRole('heading', { name: 'Turn 2 in progress', exact: true })).toBeVisible()
    await expect(bob.getByText('Completed turn 1, Sep11 11:00:00 UTC', { exact: true })).toHaveCount(1)
    await bob.reload()
    await expect(bob.getByRole('heading', { name: 'Turn 2 in progress', exact: true })).toBeVisible()
    await expect(bob.getByText('Completed turn 1, Sep11 11:00:00 UTC', { exact: true })).toHaveCount(1)
    for (let i = 0; i < 3; i++) await bob.getByLabel('Available deployment crossings').getByRole('button').first().click()
    await expect(bob.getByRole('heading', { name: /^Turn 2,/ })).toBeVisible()
    const deployment = await bob.getByLabel('Outgoing game text').inputValue()
    await jack.getByLabel('Game text or link from your partner').fill(deployment)
    await jack.getByRole('button', { name: /Load partner.s reply/ }).click()
    await jack.getByLabel('Secret Discovery Locations').getByRole('button').first().click()
    await expect(jack.getByRole('heading', { name: 'Turn 3 in progress', exact: true })).toBeVisible()
    await jack.getByLabel('Legal Jack destinations').getByRole('button').first().click()
    await expect(jack.getByRole('heading', { name: 'Turn 3 in progress', exact: true })).toBeVisible()
    await jack.getByRole('button', { name: 'Record move privately' }).click()
    const move = await jack.getByLabel('Outgoing game text').inputValue()
    expect(move).toMatch(/^03-/)
    await bob.getByLabel('Game text or link from your partner').fill(move)
    await bob.getByRole('button', { name: /Load partner.s reply/ }).click()
    await bob.getByLabel('Legal yellow Investigator destinations').getByRole('button').first().click()
    await bob.getByRole('button', { name: 'Show sharing', exact: true }).click()
    await expect(bob.getByRole('heading', { name: 'Turn 4 in progress', exact: true })).toBeVisible()
    const saved = await bob.evaluate(() => localStorage.getItem('whitehall-mystery.by-mail.v1'))
    await bob.getByLabel('Game text or link from your partner').fill(revised)
    await bob.getByRole('button', { name: /Load partner.s correction/ }).click()
    const review = bob.getByRole('alertdialog', { name: 'Review partner correction' })
    await expect(review).toContainText('2 turns differ')
    await expect(review).toContainText('Game ID: same')
    await expect(review).toContainText('Changed turn numbers: 2, 3')
    await bob.getByRole('button', { name: 'Reject correction' }).click()
    expect(await bob.evaluate(() => localStorage.getItem('whitehall-mystery.by-mail.v1'))).toBe(saved)
    await bob.getByRole('button', { name: /Load partner.s correction/ }).click()
    await bob.getByRole('button', { name: 'Accept correction' }).click()
    await expect(bob.getByRole('heading', { name: 'Deploy the Yellow Investigator' })).toBeVisible()

    await jack.clock.setFixedTime(new Date('2026-09-12T10:00:00Z'))
    jack.once('dialog', dialog => dialog.accept())
    await startJack([34, 46, 147, 159])
    const differentGame = await jack.getByLabel('Outgoing game text').inputValue()
    await bob.getByRole('button', { name: 'Show sharing', exact: true }).click()
    await bob.getByLabel('Game text or link from your partner').fill(differentGame)
    await bob.getByRole('button', { name: /Load partner.s correction/ }).click()
    await expect(review).toContainText('Game ID: different')
    await expect(review).toContainText('0 turns differ')
    await bob.getByRole('button', { name: 'Accept correction' }).click()
    await expect(bob.getByRole('heading', { name: 'Turn 2 in progress', exact: true })).toBeVisible()
    await expect(bob.getByText('Completed turn 1, Sep12 10:00:00 UTC', { exact: true })).toHaveCount(1)
  } finally { await context.close() }
})
