import { expect, test, type Page, type APIRequestContext } from '@playwright/test'
import type { OnlineSession } from '../../src/online/onlineSession'
import { observeInvitationClipboard } from './invitationClipboard'

test.beforeEach(async ({ page }) => { await observeInvitationClipboard(page) })

// Run this suite in its own local Worker invocation (npm run test:e2e) so it
// doesn't share the simulated per-IP connection quota with the other suites.
const onlineEntry = (page: Page) => page.locator('.saved-game-list li').filter({ hasText: 'Online ·' })
async function sessionFor(page: Page): Promise<OnlineSession> {
  return page.evaluate(() => JSON.parse(localStorage.getItem('whitehall-mystery.saved-game.v1.' + localStorage.getItem('whitehall-mystery.active-game.v1'))!).session)
}
async function start(page: Page, blockAutomatic = false) {
  await page.goto('/')
  await page.evaluate(block => { window.invitationClipboardProbe.blockAutomatic = block }, blockAutomatic)
  await page.getByRole('button', { name: 'New game', exact: true }).click()
  await page.getByRole('button', { name: 'Online', exact: true }).click()
  await page.getByRole('button', { name: 'Start new game as Jack' }).click()
  await expect(page.getByLabel('Online investigator invitation')).toBeVisible()
  const session = await sessionFor(page)
  expect(new URL(session.apiBase).hostname).toBe('127.0.0.1')
  return session
}
const post = (request: APIRequestContext, origin: string, session: OnlineSession, data: object) => request.post(`${session.apiBase}/v1/games/${session.roomId}/session`, {
  headers: { Origin: origin }, data: { token: session.token, ...data },
})

test('online departures: create as Investigators, share and edit names, then Leave+New Game as Jack', async ({ page: investigators, browser, request }) => {
  const context = await browser.newContext()
  const jack = await context.newPage()
  try {
    await investigators.goto('/')
    await investigators.getByRole('button', { name: 'New game', exact: true }).click()
    await investigators.getByRole('button', { name: 'Online', exact: true }).click()
    await investigators.getByLabel('Game name (optional)').fill('Friday mystery')
    await investigators.reload()
    await investigators.getByRole('button', { name: 'New game', exact: true }).click()
    await investigators.getByRole('button', { name: 'Online', exact: true }).click()
    await expect(investigators.getByLabel('Game name (optional)')).toHaveValue('Friday mystery')
    await investigators.setViewportSize({ width: 390, height: 844 })
    await investigators.screenshot({ path: 'test-results/online-creation-mobile.png', fullPage: true })
    await investigators.getByRole('button', { name: 'Start new game as Investigators', exact: true }).click()
    await expect(investigators.getByRole('heading', { name: 'Friday mystery', exact: true })).toBeVisible()
    const session = await sessionFor(investigators)
    const origin = new URL(investigators.url()).origin
    expect(new URL(session.apiBase).hostname).toBe('127.0.0.1')
    expect(session.role).toBe('investigators')
    const invitation = await investigators.getByLabel('Online Jack invitation').inputValue()
    await expect(investigators.getByLabel('Online game')).toContainText('Jack invitation copied automatically.')
    expect(await investigators.evaluate(() => navigator.clipboard.readText())).toBe(invitation)
    expect(await investigators.evaluate(() => window.invitationClipboardProbe.gestures)).toEqual([true])
    await investigators.reload()
    await expect(investigators.getByLabel('Online Jack invitation')).toHaveValue(invitation)
    expect(await investigators.evaluate(() => window.invitationClipboardProbe.writes)).toBe(0)
    expect(await investigators.evaluate(() => navigator.clipboard.readText())).toBe('Clipboard before creation')
    await jack.goto(invitation)
    await expect(jack.getByRole('heading', { name: 'Friday mystery', exact: true })).toBeVisible()
    const jackSession = await sessionFor(jack)
    expect(jackSession.role).toBe('jack')
    await jack.getByRole('button', { name: 'Rand Side', exact: true }).click()
    await expect(investigators.getByRole('heading', { name: 'Deploy the Yellow Investigator' })).toBeVisible()
    await jack.getByRole('button', { name: 'Request undo', exact: true }).click()
    await expect(jack.getByRole('button', { name: 'Cancel undo request', exact: true })).toBeEnabled()
    const blockedRename = await post(request, origin, session, { type: 'rename', requestId: crypto.randomUUID(), expectedName: 'Friday mystery', name: 'Paused game' })
    expect(blockedRename.status()).toBe(409)
    expect((await (await post(request, origin, session, { type: 'status' })).json()).undo.status).toBe('pending')
    await jack.getByRole('button', { name: 'Cancel undo request', exact: true }).click()
    await expect(jack.getByRole('button', { name: 'Request undo', exact: true })).toBeEnabled()
    const before = await (await post(request, origin, session, { type: 'status' })).json()
    await investigators.getByRole('button', { name: 'Resume game', exact: true }).click()
    await onlineEntry(investigators).getByRole('button', { name: 'Edit name', exact: true }).click()
    await investigators.getByLabel('Game name (optional)').fill('Saturday mystery 🕵️')
    const renameIds: string[] = []
    let loseRename = true
    await investigators.route('**/session', async route => {
      const data = route.request().postDataJSON()
      if (data.type !== 'rename') { await route.continue(); return }
      renameIds.push(data.requestId)
      if (loseRename) {
        loseRename = false
        expect((await route.fetch()).status()).toBe(200)
        await route.abort('failed')
      } else await route.continue()
    })
    await investigators.getByRole('button', { name: 'Save name', exact: true }).click()
    await expect(onlineEntry(investigators).getByRole('alert')).toBeVisible()
    await expect(jack.getByRole('heading', { name: 'Saturday mystery 🕵️', exact: true })).toBeVisible()
    await investigators.getByRole('button', { name: 'Save name', exact: true }).click()
    await expect(onlineEntry(investigators).locator('.saved-game-name')).toHaveText('Saturday mystery 🕵️')
    expect(renameIds).toHaveLength(2)
    expect(renameIds[0]).toBe(renameIds[1])
    const renamed = await (await post(request, origin, session, { type: 'status' })).json()
    expect(renamed.snapshot.revision).toBe(before.snapshot.revision + 1)
    expect(renamed.snapshot.history).toEqual(before.snapshot.history)
    expect(renamed.snapshot.historyHash).toBe(before.snapshot.historyHash)
    const rename = { type: 'rename', requestId: crypto.randomUUID(), expectedName: renamed.name, name: 'Tuesday' }
    expect((await post(request, origin, { ...session, token: 'X'.repeat(43) }, rename)).status()).toBe(401)
    expect((await post(request, origin, session, { ...rename, name: 'x'.repeat(81) })).status()).toBe(400)
    expect((await post(request, origin, session, { ...rename, arbitrary: 'data' })).status()).toBe(400)
    expect((await post(request, origin, session, { ...rename, expectedName: before.name })).status()).toBe(409)
    // Another rename while this editor is open must not silently overwrite it.
    await onlineEntry(investigators).getByRole('button', { name: 'Edit name', exact: true }).click()
    expect((await post(request, origin, jackSession, rename)).status()).toBe(200)
    await investigators.getByLabel('Game name (optional)').fill('Conflicting name')
    await investigators.getByRole('button', { name: 'Save name', exact: true }).click()
    await expect(onlineEntry(investigators).getByRole('alert')).toContainText('name changed')
    await investigators.getByRole('button', { name: 'Cancel name edit', exact: true }).click()
    await investigators.getByRole('button', { name: 'Refresh status', exact: true }).click()
    await expect(onlineEntry(investigators).locator('.saved-game-name')).toHaveText('Tuesday')
    await onlineEntry(investigators).getByRole('button', { name: 'Edit name', exact: true }).click()
    await investigators.getByLabel('Game name (optional)').fill('界'.repeat(80))
    expect(await investigators.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await investigators.screenshot({ path: 'test-results/resume-name-mobile.png', fullPage: true })
    await investigators.getByRole('button', { name: 'Save name', exact: true }).click()
    await expect(jack.locator('.online-game-name')).toHaveText('界'.repeat(80))
    await onlineEntry(investigators).getByRole('button', { name: 'Edit name', exact: true }).click()
    await investigators.getByLabel('Game name (optional)').fill('')
    await investigators.getByRole('button', { name: 'Save name', exact: true }).click()
    await expect(jack.locator('.online-game-name')).toHaveCount(0)
    await onlineEntry(investigators).locator('.saved-game-resume').click()
    investigators.once('dialog', dialog => dialog.accept())
    await investigators.getByRole('button', { name: 'Leave+New Game', exact: true }).click()
    await expect(investigators.getByRole('heading', { name: 'New game', exact: true })).toBeVisible()
    await expect(jack.locator('.online-departure')).toContainText('left the game')
    expect((await post(request, origin, session, { type: 'status' })).status()).toBe(401)
    await investigators.getByRole('button', { name: 'Online', exact: true }).click()
    await investigators.getByLabel('Game name (optional)').fill('Next game')
    await investigators.getByRole('button', { name: 'Start new game as Jack', exact: true }).click()
    await expect(investigators.getByLabel('Online investigator invitation')).toBeVisible()
    expect((await sessionFor(investigators)).roomId).not.toBe(session.roomId)
    await investigators.getByRole('button', { name: 'Resume game', exact: true }).click()
    await expect(onlineEntry(investigators)).toHaveCount(1)
    await expect(onlineEntry(investigators)).toContainText('Next game')
  } finally { await context.close() }
})

test('online departures: Leave+New Game keeps the current entry on failure and retries safely', async ({ page, request }) => {
  const session = await start(page, true)
  await expect(page.getByLabel('Online game')).toContainText('automatic copying was unavailable')
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('Clipboard before creation')
  await page.getByRole('button', { name: 'Copy invitation link', exact: true }).click()
  await expect(page.getByLabel('Online game')).toContainText('Investigator invitation copied.')
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(await page.getByLabel('Online investigator invitation').inputValue())
  const origin = new URL(page.url()).origin
  let fail = true
  const ids: string[] = []
  await page.route('**/session', async route => {
    const data = route.request().postDataJSON()
    if (data.type !== 'leave') { await route.continue(); return }
    ids.push(data.requestId)
    if (fail) { fail = false; await route.abort('failed') } else await route.continue()
  })
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Leave+New Game', exact: true }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'Your saved game has been kept' })).toBeVisible()
  expect((await sessionFor(page)).roomId).toBe(session.roomId)
  expect((await post(request, origin, session, { type: 'status' })).status()).toBe(200)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Leave+New Game', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'New game', exact: true })).toBeVisible()
  expect(ids[0]).toBe(ids[1])
  expect((await post(request, origin, session, { type: 'status' })).status()).toBe(401)
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(onlineEntry(page)).toHaveCount(0)
})

test('online departures: notify, preserve history, refresh the chooser, revoke old credentials, and replace either role', async ({ page: jack, browser, request }) => {
  const contexts = await Promise.all([browser.newContext(), browser.newContext(), browser.newContext()])
  const [investigators, newInvestigators, newJack] = await Promise.all(contexts.map(context => context.newPage()))
  try {
    const jackSession = await start(jack)
    const origin = new URL(jack.url()).origin
    const originalInvitation = await jack.getByLabel('Online investigator invitation').inputValue()
    await investigators.goto(originalInvitation)
    await expect(investigators.getByLabel('Online game')).toBeVisible()
    const investigatorsSession = await sessionFor(investigators)
    const badInvite = await post(request, origin, jackSession, { type: 'invite', requestId: crypto.randomUUID() })
    expect(badInvite.status()).toBe(409) // Cannot replace an active opponent.
    const extra = await post(request, origin, jackSession, { type: 'leave', requestId: crypto.randomUUID(), role: 'investigators' })
    expect(extra.status()).toBe(400) // The server selects the role from the credential.
    const oversized = await post(request, origin, jackSession, { type: 'status', payload: 'x'.repeat(1000) })
    expect(oversized.status()).toBe(413)

    await jack.getByRole('button', { name: 'Rand Side', exact: true }).click()
    await expect(investigators.getByRole('heading', { name: 'Deploy the Yellow Investigator' })).toBeVisible()
    await jack.getByRole('button', { name: 'Request undo', exact: true }).click()
    await expect(investigators.getByRole('region', { name: 'Undo request', exact: true })).toBeVisible()
    const beforeLeave = await (await post(request, origin, jackSession, { type: 'status' })).json()
    await investigators.getByRole('button', { name: 'Resume game', exact: true }).click()
    const leaving = investigators.waitForRequest(req => req.url().endsWith('/session') && req.postDataJSON()?.type === 'leave')
    investigators.once('dialog', dialog => dialog.accept())
    await onlineEntry(investigators).getByRole('button', { name: 'Leave', exact: true }).click()
    const leaveMessage = (await leaving).postDataJSON()
    await expect(onlineEntry(investigators)).toHaveCount(0)
    await expect(jack.locator('.online-departure')).toContainText('left the game')
    await expect(jack.getByLabel('Online undo')).toContainText('Undo request cancelled')
    const afterLeave = await (await post(request, origin, jackSession, { type: 'status' })).json()
    expect(afterLeave.seats.investigators.leftAt).not.toBeNull()
    expect(afterLeave.snapshot.history).toEqual(beforeLeave.snapshot.history)
    expect(afterLeave.snapshot.historyHash).toBe(beforeLeave.snapshot.historyHash)
    expect((await post(request, origin, investigatorsSession, { type: 'status' })).status()).toBe(401)
    await investigators.reload()
    await expect(onlineEntry(investigators)).toHaveCount(0)

    await jack.getByRole('button', { name: 'Resume game', exact: true }).click()
    await expect(onlineEntry(jack)).toContainText('Opponent left the game')
    await jack.setViewportSize({ width: 390, height: 844 })
    expect(await jack.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await jack.screenshot({ path: 'test-results/resume-departure-mobile.png', fullPage: true })
    await onlineEntry(jack).locator('.saved-game-resume').click()
    const inviting = jack.waitForRequest(req => req.url().endsWith('/session') && req.postDataJSON()?.type === 'invite')
    await jack.getByRole('button', { name: 'Create replacement invitation', exact: true }).click()
    const replacement = await jack.getByLabel('Online investigator invitation').inputValue()
    const inviteRetry = await post(request, origin, jackSession, (await inviting).postDataJSON())
    expect(inviteRetry.status()).toBe(200)
    expect((await inviteRetry.json()).token).toBe(new URLSearchParams(new URL(replacement).hash.slice(1)).get('online')!.split('.')[1])
    expect(replacement).not.toBe(originalInvitation)
    await newInvestigators.goto(replacement)
    await expect(newInvestigators.getByRole('heading', { name: 'Deploy the Yellow Investigator' })).toBeVisible()
    await expect(jack.locator('.online-departure')).toBeVisible()
    await newInvestigators.getByLabel('Available deployment crossings').getByRole('button').first().click()
    await expect(newInvestigators.getByRole('heading', { name: 'Deploy the Blue Investigator' })).toBeVisible()
    await expect(jack.locator('.online-departure')).toBeVisible()
    await newInvestigators.getByRole('button', { name: 'Rand Side', exact: true }).click()
    await expect(newInvestigators.getByRole('button', { name: 'Confirm deployment' })).toBeVisible()
    await expect(jack.locator('.online-departure')).toBeVisible()
    await newInvestigators.getByRole('button', { name: 'Confirm deployment' }).click()
    await expect(jack.getByRole('heading', { name: 'Jack: Choose the Starting Location' })).toBeVisible()
    await expect(jack.locator('.online-departure')).toHaveCount(0)
    // Retry an old acknowledged Leave: it must not evict the replacement.
    expect((await post(request, origin, investigatorsSession, leaveMessage)).status()).toBe(200)
    const activeAgain = await (await post(request, origin, jackSession, { type: 'status' })).json()
    expect(activeAgain.seats.investigators.leftAt).toBeNull()
    expect((await post(request, origin, investigatorsSession, { type: 'leave', requestId: crypto.randomUUID() })).status()).toBe(401)

    // Leave an INACTIVE online game while keeping another saved game intact.
    await jack.getByRole('button', { name: 'New game', exact: true }).click()
    await jack.getByRole('button', { name: 'Same device', exact: true }).click()
    await jack.getByLabel('Location 33, selectable', { exact: true }).click()
    await jack.getByRole('button', { name: 'Resume game', exact: true }).click()
    // The remaining player is already in the chooser, with no game socket.
    await newInvestigators.getByRole('button', { name: 'Resume game', exact: true }).click()
    await expect(onlineEntry(newInvestigators)).not.toContainText('Opponent left the game')
    jack.once('dialog', dialog => dialog.accept())
    await onlineEntry(jack).getByRole('button', { name: 'Leave', exact: true }).click()
    await expect(onlineEntry(jack)).toHaveCount(0)
    await jack.getByRole('button', { name: 'Cancel', exact: true }).click()
    await expect(jack.getByLabel('1 player actions', { exact: true })).toBeVisible()
    await newInvestigators.getByRole('button', { name: 'Refresh status', exact: true }).click()
    await expect(onlineEntry(newInvestigators)).toContainText('Opponent left the game')
    await onlineEntry(newInvestigators).locator('.saved-game-resume').click()
    await expect(newInvestigators.locator('.online-departure')).toContainText('Jack')
    await newInvestigators.getByRole('button', { name: 'Create replacement invitation', exact: true }).click()
    const jackInvitation = await newInvestigators.getByLabel('Online Jack invitation').inputValue()
    expect(new URLSearchParams(new URL(jackInvitation).hash.slice(1)).get('role')).toBe('jack')
    await newJack.goto(jackInvitation)
    await expect(newJack.getByRole('heading', { name: 'Jack: Choose the Starting Location' })).toBeVisible()
    await newJack.getByLabel('Secret Discovery Locations').getByRole('button').first().click()
    await newJack.getByLabel('Legal Jack destinations').getByRole('button').first().click()
    await expect(newInvestigators.locator('.online-departure')).toBeVisible()
    await newJack.getByRole('button', { name: 'Record move privately' }).click()
    await expect(newInvestigators.getByRole('heading', { name: 'Yellow Investigator: Move' })).toBeVisible()
    await expect(newInvestigators.locator('.online-departure')).toHaveCount(0)
    expect((await post(request, origin, jackSession, { type: 'status' })).status()).toBe(401)
    await newInvestigators.getByRole('button', { name: 'Resume game', exact: true }).click()
    await expect(onlineEntry(newInvestigators)).not.toContainText('Opponent left the game')
  } finally { await Promise.all(contexts.map(context => context.close())) }
})

test('online departures: a lost leave acknowledgement keeps the entry until an idempotent retry succeeds', async ({ page, request }) => {
  const session = await start(page)
  const origin = new URL(page.url()).origin
  await page.getByRole('button', { name: 'Resume game', exact: true }).click()
  const requestIds: string[] = []
  let loseResponse = true
  await page.route('**/session', async route => {
    const body = route.request().postDataJSON()
    if (body?.type !== 'leave') { await route.continue(); return }
    requestIds.push(body.requestId)
    if (loseResponse) {
      loseResponse = false
      const result = await route.fetch()
      expect(result.status()).toBe(200)
      await route.abort('failed')
    } else await route.continue()
  })
  page.once('dialog', dialog => dialog.accept())
  await onlineEntry(page).getByRole('button', { name: 'Leave', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'saved entry has been kept' })).toBeVisible()
  await expect(onlineEntry(page)).toHaveCount(1)
  expect((await post(request, origin, session, { type: 'status' })).status()).toBe(401)
  page.once('dialog', dialog => dialog.accept())
  await onlineEntry(page).getByRole('button', { name: 'Leave', exact: true }).click()
  await expect(onlineEntry(page)).toHaveCount(0)
  expect(requestIds).toHaveLength(2)
  expect(requestIds[1]).toBe(requestIds[0])
  await page.reload()
  await expect(onlineEntry(page)).toHaveCount(0)
})
