import { expect, test } from '@playwright/test'

test.use({ timezoneId: 'America/Chicago' })

test('compact Edit name sits beside the name inside the card without resuming the game', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Resume game', exact: true }).click()
  const edit = page.getByRole('button', { name: 'Edit name', exact: true })
  await expect(page.locator('.saved-game-name-row')).toContainText('Unnamed game')
  await edit.click()
  await expect(page.getByRole('heading', { name: 'Resume game', exact: true })).toBeVisible()
  await page.getByLabel('Game name (optional)').fill('Friday game')
  await page.getByRole('button', { name: 'Save name', exact: true }).click()
  for (const width of [1000, 390]) {
    await page.setViewportSize({ width, height: 844 })
    const nameBox = (await page.locator('.saved-game-name').boundingBox())!
    const editBox = (await edit.boundingBox())!
    const cardBox = (await page.locator('.saved-game-card').boundingBox())!
    expect(editBox.x).toBeGreaterThan(nameBox.x + nameBox.width)
    expect(editBox.y).toBeLessThan(nameBox.y + nameBox.height)
    expect(editBox.x + editBox.width).toBeLessThan(cardBox.x + cardBox.width)
    expect(editBox.height).toBeLessThan((await page.getByRole('button', { name: 'Leave', exact: true }).boundingBox())!.height)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `test-results/inline-edit-name-${width}.png`, fullPage: true })
  }
  await expect(page.locator('button button, button input')).toHaveCount(0)
  await edit.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByLabel('Game name (optional)')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Resume game', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Cancel name edit', exact: true }).click()
  // The name still belongs to the card's resume hit area, not just the details.
  await page.locator('.saved-game-name').click({ force: true })
  await expect(page.getByRole('heading', { name: 'Jack: Plan the Crime', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Resume game', exact: true }).click()
  await page.getByRole('button', { name: /Friday game/ }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Jack: Plan the Crime', exact: true })).toBeVisible()
})

test('Leave+New Game confirms, removes only the current game, and opens creation; names persist locally', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Location 33, selectable', { exact: true }).click()
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: 'Leave+New Game', exact: true }).click()
  await expect(page.getByLabel('1 player actions', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Resume game', exact: true }).click()
  await page.getByRole('button', { name: 'Edit name', exact: true }).click()
  await page.getByLabel('Game name (optional)').fill('Keep this game')
  await page.getByRole('button', { name: 'Save name', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: 'Resume game', exact: true }).click()
  await expect(page.locator('.saved-game-name')).toHaveText('Keep this game')
  await page.getByRole('button', { name: 'New game', exact: true }).click()
  await page.getByRole('button', { name: 'By Mail', exact: true }).click()
  await page.getByRole('button', { name: 'Start new game as Jack' }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Leave+New Game', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'New game', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Same device', exact: true }).click()
  await expect(page.getByLabel('0 player actions', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Resume game', exact: true }).click()
  await expect(page.locator('.saved-game-resume')).toHaveCount(2)
  await expect(page.locator('.saved-game-resume').filter({ hasText: 'By Mail' })).toHaveCount(0)
  await page.getByRole('button', { name: /Keep this game/ }).click()
  await expect(page.getByLabel('1 player actions', { exact: true })).toBeVisible()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Leave+New Game', exact: true }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.locator('.saved-game-resume')).toHaveCount(1)
  await expect(page.locator('.saved-game-name')).toHaveCount(0)
})

test('Leave removes local games, supports cancellation, and keeps the last-game empty state on reload', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Location 33, selectable', { exact: true }).click()
  await page.getByRole('button', { name: 'Resume game', exact: true }).click()
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: 'Leave', exact: true }).click()
  await expect(page.locator('.saved-game-resume')).toHaveCount(1)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Leave', exact: true }).click()
  await expect(page.getByText('No saved games.', { exact: false })).toBeVisible()
  await page.reload()
  await expect(page.locator('.saved-game-resume')).toHaveCount(0)
  await page.getByRole('button', { name: 'New game', exact: true }).click()
  await page.getByRole('button', { name: 'By Mail', exact: true }).click()
  await page.getByRole('button', { name: 'Start new game as Jack' }).click()
  await page.getByRole('button', { name: 'Resume game', exact: true }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Leave', exact: true }).click()
  await page.reload()
  await expect(page.locator('.saved-game-resume')).toHaveCount(0)
})

test('same-device games preserve full undo history and resume from the handoff screen', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-24T14:00:00Z'))
  await page.goto('/')
  await page.getByLabel('Location 33, selectable', { exact: true }).click()
  await page.getByLabel('Location 46, selectable', { exact: true }).click()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.clock.setFixedTime(new Date('2026-09-24T15:00:00Z'))
  await page.getByRole('button', { name: 'New game', exact: true }).click()
  await page.getByRole('button', { name: 'Same device', exact: true }).click()
  await expect(page.getByLabel('0 player actions', { exact: true })).toBeVisible()
  await page.getByLabel('Location 147, selectable', { exact: true }).click()
  await page.getByRole('button', { name: 'Resume game', exact: true }).click()
  const first = page.locator('.saved-game-list button').filter({ hasText: '2026-09-24 09:00:00 CDT' })
  await expect(first).toContainText('Same device')
  await expect(first).toContainText('Round 1 · Move 0 · Jack’s turn')
  await expect(page.locator('.saved-game-resume')).toHaveCount(2)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/resume-game-mobile.png', fullPage: true })
  await first.click()
  await page.reload()
  await expect(page.getByLabel('1 player actions', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(page.getByLabel('2 player actions', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Rand Side', exact: true }).click()
  await page.getByRole('button', { name: 'Rand Side', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Pass the device to Jack' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'New game', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Resume game', exact: true }).click()
  await page.locator('.saved-game-list button').filter({ hasText: '2026-09-24 10:00:00 CDT' }).click()
  await expect(page.getByLabel('1 player actions', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.getByLabel('0 player actions', { exact: true })).toBeVisible()
})

test('multiple By Mail games retain separate drafts, sharing views and undo tails', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-24T16:00:00Z'))
  await page.goto('/')
  const startMail = async () => {
    await page.getByRole('button', { name: 'New game', exact: true }).click()
    await page.getByRole('button', { name: 'By Mail', exact: true }).click()
    await page.getByRole('button', { name: 'Start new game as Jack' }).click()
  }
  await startMail()
  await page.getByRole('button', { name: 'Rand Side', exact: true }).click()
  const outgoing = await page.getByLabel('Outgoing game text').inputValue()
  await page.getByLabel('Game text or link from your partner').fill('unfinished reply for first game')
  await page.getByRole('button', { name: 'Show board', exact: true }).click()
  await page.clock.setFixedTime(new Date('2026-09-24T17:00:00Z'))
  await startMail()
  await page.getByLabel('Location 46, selectable', { exact: true }).click()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.getByRole('button', { name: 'Resume game', exact: true }).click()
  const games = page.locator('.saved-game-list button').filter({ hasText: 'By Mail · Jack' })
  await expect(games).toHaveCount(2)
  await expect(games.filter({ hasText: '11:00:00 CDT' })).toContainText('Investigators’ turn')
  await games.filter({ hasText: '11:00:00 CDT' }).click()
  await expect(page.getByRole('button', { name: 'Show sharing', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Show sharing', exact: true }).click()
  await expect(page.getByLabel('Game text or link from your partner')).toHaveValue('unfinished reply for first game')
  await expect(page.getByLabel('Outgoing game text')).toHaveValue(outgoing)
  await page.getByRole('button', { name: 'New game', exact: true }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByLabel('Outgoing game text')).toHaveValue(outgoing)
  await page.getByRole('button', { name: 'Resume game', exact: true }).click()
  await games.filter({ hasText: '12:00:00 CDT' }).click()
  await page.reload()
  await expect(page.getByLabel('0 player actions', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(page.getByLabel('1 player actions', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Show sharing', exact: true }).click()
  await expect(page.getByLabel('Game text or link from your partner')).toBeEmpty()
})
